name: ocd
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.0
  flutter_svg: ^1.0.3
  pin_code_fields: ^7.4.0
  linear_step_indicator: ^1.0.0+3
  neon_circular_timer: ^0.0.7
  carousel_slider: ^4.1.1
  rflutter_alert: ^2.0.4
  get: ^4.5.1
  get_storage: ^2.0.3
  cached_network_image: ^3.2.0
#  navigation_dot_bar: ^0.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
     - assets/icons/




